
# Required: A short name for the action package
name: Financial Action Package

# Required: A description of what's in the action package.
description: Action package description

# Required: A link to where the documentation on the package lives.
documentation: https://github.com/<path to your markdown>/README.md

dependencies:
  conda-forge:
  - python=3.10.14
  - uv=0.1.44
  pypi:
  - sema4ai-actions=0.6.0
  - phidata=2.4.10
  - yfinance=0.2.38

packaging:
  # This section is optional.
  # By default all files and folders in this directory are packaged when uploaded.
  # Add exclusion rules below (expects glob format: https://docs.python.org/3/library/glob.html)
  exclude:
    - ./.git/**
    - ./.vscode/**
    - ./devdata/**
    - ./output/**
    - ./.DS_store/**
    - ./venv/**
    - ./.venv/**
    - ./**/*.pyc
    - ./**/*.zip
